name: 'Setup MySQL with Python 2.7'
description: 'Setup a MySQL database with Python 2.7'
author: 'Griffin Kelly'
branding:
  icon: check-circle
  color: green
inputs:
  host port:
    description: 'The port of host'
    required: false
    default: 3306
  container port:
    description: 'The port of container'
    required: false
    default: 3306
  character set server:
    description: '--character-set-server - The character set of MySQL server'
    required: false
    default: 'utf8mb4'
  collation server:
    description: '--collation-server - The character collation of MySQL server'
    required: false
    default: 'utf8mb4_general_ci'
  mysql version:
    description: 'Version of MySQL to use'
    required: false
    default: 'latest'
  mysql root password:
    description: 'MYSQL_ROOT_PASSWORD - root superuser password'
    required: false
    default: ''
  mysql database:
    description: 'MYSQL_DATABASE - name for the default database that is created'
    required: false
    default: ''
  mysql user:
    description: 'MYSQL_USER - create the specified user with superuser power for created database'
    required: false
    default: ''
  mysql password:
    description: 'MYSQL_PASSWORD - specified superuser password which user is power for created database'
    required: false
    default: ''
  settings path:
    description: "The path of the directory containing the settings file(Without `./`)"
    required: false
    default: './'
  parallel tests:
    description: "Run tests in parallel"
    default: false
    required: false
  requirements file:
    description: "The path of dependancy file, typically requirements.txt"
    default: "requirements.txt"
    required: false
  env file:
    description: "The path of an env file, if you require environment variables"
    default: ""
    required: false
  test apps:
    description: "Specific apps you want to test"
    default: ""
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
